# Use official OpenJDK image
FROM eclipse-temurin:17-jdk-alpine

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Build the application
RUN ./mvnw clean package -DskipTests

# Expose the port
EXPOSE 8080

# Run the jar file
CMD ["java", "-jar", "target/proyecto-juego-backend-0.0.1-SNAPSHOT.jar"]
